const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { loadScripts } = require('./test-helpers');
const centralTime = loadScripts(['time-utils.js']);
const preview = fs.readFileSync('planung2-preview.html', 'utf8');
function extract(name) { const start=preview.indexOf(`function ${name}`); assert.notEqual(start,-1,`${name} exists`); let depth=0,open=false; for(let i=start;i<preview.length;i++){if(preview[i]==='{'){depth++;open=true}else if(preview[i]==='}'&&--depth===0&&open)return preview.slice(start,i+1)} throw Error(name) }
function loadApi(){const c=vm.createContext({iso:d=>d.toISOString().slice(0,10),mins:v=>{const [h,m]=v.split(':').map(Number);return h*60+m},hm:m=>`${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`,getBusinessRequiredBreakMinutes:centralTime.getBusinessRequiredBreakMinutes,getWorkedMinutesFromRange:centralTime.getWorkedMinutesFromRange});vm.runInContext([
 'function resolvedShiftTimes(r){return r?.type==="shift"?{start:r.sourceEntry.start,end:r.sourceEntry.end}:null}',
 'function getPlanning2EmployeeWeekEvaluation(e,d,r){let actual=r.reduce((n,x)=>n+(x.minutesForMonth||0),0),isGfb=e.roleKey==="GFB",target=isGfb?null:(e.targetMinutes??1800),difference=isGfb?0:actual-target;return{weeklyActualMinutes:actual,weeklyTargetMinutes:target,differenceMinutes:difference,isGfb,hasRegularFreeDay:e.hasFree!==false,summary:{actualMinutes:actual,targetMinutes:target,differenceMinutes:difference,isGfb},freeDay:{hasRegularFreeDay:e.hasFree!==false}}}',
 extract('evaluateResolvedDayCoverage'),extract('recalculatePlanning2ShiftTimes'),extract('buildPlanning2OptimizationContext'),extract('getPlanning2AllowedAdjustmentTimes'),extract('escapePlanning2Html'),extract('planning2GapResolved'),extract('getPlanning2CandidateRankingData'),extract('comparePlanning2OptimizationCandidates'),extract('buildPlanning2OptimizationSuggestions'),'this.api={buildPlanning2OptimizationContext,buildPlanning2OptimizationSuggestions,getPlanning2AllowedAdjustmentTimes,getPlanning2CandidateRankingData,comparePlanning2OptimizationCandidates,escapePlanning2Html}'
].join(';'),c);c.api.setEvaluate=fn=>{c.evaluateResolvedDayCoverage=fn};return c.api}
const day=new Date('2026-08-24T00:00:00Z');
const shift=(start,end,minutesForMonth=0)=>({type:'shift',minutesForMonth,sourceEntry:{type:'shift',start,end}});
function suggestions(employees,entries){const api=loadApi(),resolved=entries.map(entry=>[entry]),context=api.buildPlanning2OptimizationContext(employees,[day],resolved);return{context,result:api.buildPlanning2OptimizationSuggestions(context),resolved}}

test('grid generation rejects arbitrary gap minutes and keeps 30-minute choices before quarters',()=>{const api=loadApi();for(const minute of [5,10,20,25,35,40,50,55]){const times=api.getPlanning2AllowedAdjustmentTimes('13:00',14*60+minute,'extend-end');assert.ok(times.every(x=>[0,15,30,45].includes(x.minutes%60)));assert.ok(!times.some(x=>x.minutes%60===minute),`:${minute} was copied`);const quarter=times.findIndex(x=>x.minutes%30!==0);assert.ok(quarter<0||times.slice(0,quarter).every(x=>x.minutes%30===0))}assert.deepEqual(Array.from(api.getPlanning2AllowedAdjustmentTimes('13:00',845,'extend-end'),x=>x.time),['14:00','14:15'])});

test('13:00–14:05 is exact while the read-only suggestion ends at 14:00',()=>{const employees=[{id:'base',roleKey:'TZ'},{id:'anna',name:'Anna',roleKey:'TZ',functionKey:'SV'},{id:'late',roleKey:'TZ'}],entries=[shift('08:55','19:10',600),shift('09:00','13:00',240),shift('14:05','19:10',305)],before=JSON.stringify({employees,entries}),built=suggestions(employees,entries),anna=built.result.find(x=>x.employeeId==='anna');assert.deepEqual(Array.from(built.context.days[0].coverage.gaps,g=>[g.start,g.end]),[[780,845]]);assert.equal(anna.proposedEnd,'14:00');assert.equal(anna.timeGrid,'hour');assert.equal(anna.projectedWeeklyActualMinutes,300);assert.equal(JSON.stringify({employees,entries}),before)});

test('quarter-hour is tested only after an insufficient 30-minute simulation',()=>{const api=loadApi(),employees=[{id:'anna',name:'Anna',roleKey:'TZ'}],resolved=[[shift('09:00','13:00')]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:875,required:2}]};api.setEvaluate(entries=>{const minute=Number(entries[0].sourceEntry.end.slice(0,2))*60+Number(entries[0].sourceEntry.end.slice(3));return{ok:minute>=885,gaps:minute>=885?[]:[{kind:'understaffing',start:780,end:875}]}});const result=api.buildPlanning2OptimizationSuggestions(context)[0];assert.equal(result.proposedEnd,'14:45');assert.equal(result.timeGrid,'quarter-hour')});

test('30-minute grid beats a quarter-hour option whenever its simulation succeeds',()=>{const api=loadApi(),employees=[{id:'half',roleKey:'TZ'}],resolved=[[shift('09:00','13:00')]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:875,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const result=api.buildPlanning2OptimizationSuggestions(context)[0];assert.equal(result.proposedEnd,'14:30');assert.equal(result.timeGrid,'half-hour')});

test('advance-start follows the same grid priority and preserves an existing 19:10 end',()=>{const api=loadApi(),employees=[{id:'ben',roleKey:'TZ'}],resolved=[[shift('14:05','19:10')]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:845,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const ben=api.buildPlanning2OptimizationSuggestions(context)[0];assert.equal(ben.proposedStart,'13:00');assert.equal(ben.proposedEnd,'19:10');assert.notEqual(ben.proposedStart,'08:55')});

test('changing an end preserves 08:55 and general suggestions create neither special boundary',()=>{const built=suggestions([{id:'opener',roleKey:'TZ'},{id:'base',roleKey:'TZ'},{id:'late',roleKey:'TZ'}],[shift('08:55','13:00'),shift('09:00','19:10'),shift('14:05','19:10')]);const opener=built.result.find(x=>x.employeeId==='opener');assert.equal(opener.proposedStart,'08:55');assert.equal(opener.proposedEnd,'14:00');assert.ok(built.result.every(x=>x.proposedStart!=='08:55'||x.currentStart==='08:55'));assert.ok(built.result.every(x=>x.proposedEnd!=='19:10'||x.currentEnd==='19:10'))});

test('only resolved shifts qualify even when every non-work state hides old shift times',()=>{for(const type of ['vacation','sick','off','holiday','external-help','empty']){const built=suggestions([{id:'base',roleKey:'TZ'},{id:'hidden',roleKey:'TZ'},{id:'late',roleKey:'TZ'}],[shift('08:55','19:10'),{type,sourceEntry:{type:'shift',start:'09:00',end:'13:00'}},shift('14:05','19:10')]);assert.ok(!built.result.some(x=>x.employeeId==='hidden'),type)}});

test('two gaps remain separate and independently suggest both sides of the same middle shift',()=>{const built=suggestions([{id:'base',roleKey:'TZ'},{id:'middle',roleKey:'TZ'},{id:'morning',roleKey:'TZ'},{id:'late',roleKey:'TZ'}],[shift('08:55','19:10'),shift('10:05','13:00'),shift('08:55','09:00'),shift('14:05','19:10')]);assert.deepEqual(Array.from(built.context.days[0].coverage.gaps,g=>[g.start,g.end]),[[540,605],[780,845]]);assert.equal(built.result.length,2);assert.deepEqual(Array.from(built.result,x=>[x.understaffingWindow.start,x.understaffingWindow.end]),[[540,605],[780,845]])});

test('GFB is eligible without an artificial target or projected difference',()=>{const built=suggestions([{id:'base',roleKey:'TZ'},{id:'gfb',roleKey:'GFB'},{id:'late',roleKey:'TZ',targetMinutes:100}],[shift('08:55','19:10'),shift('09:00','13:00',240),shift('14:05','19:10',305)]),gfb=built.result.find(x=>x.employeeId==='gfb');assert.equal(gfb.weeklyTargetMinutes,null);assert.equal(gfb.projectedDifferenceMinutes,null)});

test('central ranking prefers an employee below target over one above target',()=>{const built=rankSuggestions([{id:'plus',roleKey:'TZ',targetMinutes:100,actual:300},{id:'minus',roleKey:'TZ',targetMinutes:500,actual:300}]);assert.equal(built.result[0].employeeId,'minus');assert.equal(built.result[0].ranking.targetStatus,'under')});

test('central ranking prefers the larger useful deficit',()=>{const built=rankSuggestions([{id:'small-minus',roleKey:'TZ',targetMinutes:360,actual:300},{id:'large-minus',roleKey:'TZ',targetMinutes:600,actual:300}]);assert.equal(built.result[0].employeeId,'large-minus');assert.equal(built.result[0].ranking.deficitMinutes,300)});

test('a meaningfully larger deficit wins despite a somewhat longer extension',()=>{const built=rankSuggestions([{id:'large-minus',roleKey:'TZ',targetMinutes:900,actual:300},{id:'short-small-minus',roleKey:'TZ',targetMinutes:360,actual:300}],['13:00','13:30']);assert.equal(built.result[0].employeeId,'large-minus');assert.equal(built.result[0].changeMinutes,60)});

test('TZ below target ranks before an eligible GFB',()=>{const built=rankSuggestions([{id:'gfb',roleKey:'GFB',actual:300},{id:'tz-minus',roleKey:'TZ',targetMinutes:600,actual:300}]);assert.equal(built.result[0].employeeId,'tz-minus')});

test('GFB ranks before normal candidates that already met or exceeded target',()=>{const built=rankSuggestions([{id:'plus',roleKey:'TZ',targetMinutes:200,actual:300},{id:'gfb',roleKey:'GFB',actual:300},{id:'met',roleKey:'TZ',targetMinutes:300,actual:300}]);assert.equal(built.result[0].employeeId,'gfb')});

test('an otherwise suitable employee without a regular free day ranks later',()=>{const built=rankSuggestions([{id:'no-free',roleKey:'TZ',targetMinutes:600,actual:300,hasFree:false},{id:'with-free',roleKey:'TZ',targetMinutes:600,actual:300,hasFree:true}]);assert.equal(built.result[0].employeeId,'with-free');assert.equal(built.result[0].ranking.hasRegularFreeDay,true)});

test('a regular free day outweighs a small adjustment saving at the same deficit',()=>{const built=rankSuggestions([{id:'with-free',roleKey:'TZ',targetMinutes:600,actual:300,hasFree:true},{id:'no-free',roleKey:'TZ',targetMinutes:600,actual:300,hasFree:false}],['13:00','13:30']);assert.equal(built.result[0].employeeId,'with-free');assert.equal(built.result[0].changeMinutes,60)});

test('GFB ranking has no invented weekly target, difference, or deficit',()=>{const api=loadApi(),ranking=api.getPlanning2CandidateRankingData({employeeId:'gfb',isGfb:true,weeklyTargetMinutes:null,differenceMinutes:0,weeklyActualMinutes:300,changeMinutes:60,hasRegularFreeDay:true});assert.equal(ranking.targetStatus,'gfb');assert.equal(ranking.deficitMinutes,null)});

test('smaller necessary adjustment breaks ties between otherwise equal candidates',()=>{const built=rankSuggestions([{id:'long',roleKey:'TZ',targetMinutes:600,actual:300},{id:'short',roleKey:'TZ',targetMinutes:600,actual:300}],['13:00','13:30']);assert.equal(built.result[0].employeeId,'short');assert.equal(built.result[0].changeMinutes,30)});

test('candidate is rejected when its simulation creates a new understaffing gap',()=>{const api=loadApi(),employees=[{id:'unsafe',roleKey:'TZ',targetMinutes:600},{id:'safe',roleKey:'TZ',targetMinutes:600}],resolved=[[shift('09:00','13:00',300)],[shift('09:00','13:00',300)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:845,required:2}]};api.setEvaluate(entries=>entries[0].sourceEntry.end!=='13:00'?{ok:false,gaps:[{kind:'understaffing',start:780,end:840},{kind:'understaffing',start:900,end:930}]}:{ok:true,gaps:[]});const result=api.buildPlanning2OptimizationSuggestions(context);assert.equal(result[0].employeeId,'safe')});

function rankSuggestions(people,ends){const api=loadApi(),resolved=(ends||people.map(()=> '13:00')).map((end,index)=>[shift('09:00',end,people[index].actual||0)]),context=api.buildPlanning2OptimizationContext(people,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:845,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));return{result:api.buildPlanning2OptimizationSuggestions(context),context}}

test('Saturday dates work normally and every simulation leaves nested inputs byte-identical',()=>{const employees=[{id:'base',roleKey:'TZ'},{id:'anna',roleKey:'TZ'},{id:'late',roleKey:'TZ'}],entries=[shift('08:55','19:10'),shift('09:00','13:00'),shift('14:05','19:10')],resolved=entries.map(x=>[x]),before=JSON.stringify({employees,resolved}),api=loadApi(),context=api.buildPlanning2OptimizationContext(employees,[new Date('2026-08-29T00:00:00Z')],resolved);api.buildPlanning2OptimizationSuggestions(context);assert.equal(context.days[0].isoDate,'2026-08-29');assert.equal(JSON.stringify({employees,resolved}),before)});

test('suggestion employee names are centrally HTML escaped',()=>{assert.equal(loadApi().escapePlanning2Html(`A&B <C> \"D\" 'E'`),'A&amp;B &lt;C&gt; &quot;D&quot; &#39;E&#39;');assert.match(extract('render'),/escapePlanning2Html\(item\.employeeName\)/)});

test('GFB month budget allows exactly 42:00 plus 1:00',()=>{const api=loadApi(),employees=[{id:'gfb',roleKey:'GFB'}],resolved=[[shift('09:00','13:00',240)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved,{gfb:{gfbMonthActualMinutes:2520,gfbMonthLimitMinutes:2580,gfbMonthRemainingMinutes:60}});context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const result=api.buildPlanning2OptimizationSuggestions(context);assert.equal(result.length,1);assert.equal(result[0].changeMinutes,60);assert.equal(result[0].gfbMonthActualMinutes,2520);assert.equal(result[0].gfbMonthLimitMinutes,2580);assert.equal(result[0].gfbMonthRemainingMinutes,60)});

test('GFB month budget rejects 42:30 plus 1:00',()=>{const api=loadApi(),employees=[{id:'gfb',roleKey:'GFB'}],resolved=[[shift('09:00','13:00',240)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved,{gfb:{gfbMonthActualMinutes:2550,gfbMonthLimitMinutes:2580,gfbMonthRemainingMinutes:30}});context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));assert.deepEqual(Array.from(api.buildPlanning2OptimizationSuggestions(context)),[])});

test('GFB budget filtering does not change normal employee eligibility',()=>{const api=loadApi(),employees=[{id:'normal',roleKey:'TZ',targetMinutes:600}],resolved=[[shift('09:00','13:00',240)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));assert.equal(api.buildPlanning2OptimizationSuggestions(context)[0].employeeId,'normal')});

test('GFB budget uses additional monthly work minutes across the break threshold',()=>{const api=loadApi(),employees=[{id:'gfb',roleKey:'GFB'}],resolved=[[shift('09:00','14:30',330)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved,{gfb:{gfbMonthActualMinutes:2580,gfbMonthLimitMinutes:2580,gfbMonthDifferenceMinutes:0,gfbMonthRemainingMinutes:0}});context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:870,end:930,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const result=api.buildPlanning2OptimizationSuggestions(context);assert.equal(result.length,1);assert.equal(result[0].changeMinutes,60);assert.equal(result[0].gfbMonthAdditionalMinutes,0);assert.equal(result[0].proposedEnd,'15:30')});

test('GFB already above 43:00 cannot receive additional monthly work minutes',()=>{const api=loadApi(),employees=[{id:'gfb',roleKey:'GFB'}],resolved=[[shift('09:00','13:00',240)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved,{gfb:{gfbMonthActualMinutes:2640,gfbMonthLimitMinutes:2580,gfbMonthDifferenceMinutes:-60,gfbMonthRemainingMinutes:0}});context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));assert.deepEqual(Array.from(api.buildPlanning2OptimizationSuggestions(context)),[])});
