const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { loadScripts } = require('./test-helpers');
const preview = fs.readFileSync('planung2-preview.html', 'utf8');
const centralTime = loadScripts(['time-utils.js']);
function extract(name){const start=preview.indexOf(`function ${name}`);assert.notEqual(start,-1,`${name} exists`);let depth=0,open=false;for(let i=start;i<preview.length;i++){if(preview[i]==='{'){depth++;open=true}else if(preview[i]==='}'&&--depth===0&&open)return preview.slice(start,i+1)}throw Error(name)}
function harness(plan,suggestion,{fresh=[suggestion],resolved=true,employees=[{id:suggestion.employeeId,name:'Anna'}]}={}){
  let stored=structuredClone(plan),renders=0,toasts=[],autofixes=[];
  const context=vm.createContext({
    TEST_PLAN:'test',PREVIEW_MASTER:'master',active:()=>true,clone:structuredClone,
    getTestPlan:()=>structuredClone(stored),load:()=>({employees}),
    save:(_key,value)=>{stored=structuredClone(value)},render:()=>{renders++},
    toast:(...args)=>toasts.push(args),getCurrentPlanning2OptimizationSuggestions:value=>structuredClone(typeof fresh==='function'?fresh(value):fresh),
    planning2ResolvedWorkShift:(value,employee,isoDate)=>resolved?value.schedule?.[isoDate]?.[employee.id]:null,
    applyPlanning2OptimizationAutofixes:(_plan,_employees,isoDate)=>{autofixes.push(isoDate);return{changedIds:[],warning:''}},
    getBusinessRequiredBreakMinutes:centralTime.getBusinessRequiredBreakMinutes,
    getWorkedMinutesFromRange:centralTime.getWorkedMinutesFromRange
  });
  vm.runInContext(`${extract('planning2SuggestionKey')};${extract('recalculatePlanning2ShiftTimes')};let planning2OptimizationUndo=null;${extract('applyPlanning2OptimizationSuggestion')};${extract('undoPlanning2Optimization')};this.api={applyPlanning2OptimizationSuggestion,undoPlanning2Optimization}`,context);
  return{api:context.api,state:()=>structuredClone(stored),renders:()=>renders,toasts,autofixes};
}
const isoDate='2026-08-24';
const base={isoDate,employeeId:'anna',direction:'extend-end',proposedStart:'09:00',proposedEnd:'14:00'};
const shift={type:'shift',status:'work',code:'F4',shiftKey:'F4',mode:'early',shiftType:'early',start:'09:00',end:'13:00',pause:0,breakMinutes:0,minutes:240,custom:'kept'};

test('one accepted extend-end changes only its shift, preserves metadata, and centrally recalculates time fields',()=>{const plan={schedule:{[isoDate]:{anna:shift,ben:{type:'shift',start:'09:00',end:'19:10',minutes:580}}},absences:[]},h=harness(plan,base);assert.equal(h.api.applyPlanning2OptimizationSuggestion(base),true);const result=h.state();assert.equal(result.schedule[isoDate].anna.end,'14:00');assert.equal(result.schedule[isoDate].anna.start,'09:00');assert.equal(result.schedule[isoDate].anna.pause,0);assert.equal(result.schedule[isoDate].anna.breakMinutes,0);assert.equal(result.schedule[isoDate].anna.minutes,300);assert.equal(result.schedule[isoDate].anna.custom,'kept');assert.deepEqual(result.schedule[isoDate].ben,plan.schedule[isoDate].ben);assert.deepEqual(h.autofixes,[isoDate])});

test('accepted full-day suggestion gets pause and work minutes exclusively from central time rules',()=>{for(const proposedStart of ['08:55','09:00'])for(const proposedEnd of ['19:00','19:10']){const suggestion={...base,proposedStart,proposedEnd},plan={schedule:{[isoDate]:{anna:shift}},absences:[]},h=harness(plan,suggestion);assert.equal(h.api.applyPlanning2OptimizationSuggestion(suggestion),true,`${proposedStart}–${proposedEnd}`);const result=h.state().schedule[isoDate].anna,expectedPause=centralTime.getBusinessRequiredBreakMinutes(proposedStart,proposedEnd);assert.equal(result.pause,expectedPause,`${proposedStart}–${proposedEnd} pause`);assert.equal(result.breakMinutes,expectedPause,`${proposedStart}–${proposedEnd} breakMinutes`);assert.equal(result.minutes,centralTime.getWorkedMinutesFromRange(proposedStart,proposedEnd,expectedPause),`${proposedStart}–${proposedEnd} minutes`);assert.equal(result.withCheckout,proposedEnd==='19:10',`${proposedStart}–${proposedEnd} withCheckout`)}});

test('advance-start preserves 19:10 and recalculates checkout, pause, and minutes',()=>{const suggestion={...base,direction:'advance-start',proposedStart:'13:30',proposedEnd:'19:10'},plan={schedule:{[isoDate]:{anna:{...shift,start:'14:30',end:'19:10',withCheckout:true}}},absences:[]},h=harness(plan,suggestion);assert.equal(h.api.applyPlanning2OptimizationSuggestion(suggestion),true);assert.deepEqual({...h.state().schedule[isoDate].anna},{...shift,start:'13:30',end:'19:10',withCheckout:true,pause:10,breakMinutes:10,minutes:330})});

test('central break threshold keeps exactly six hours break-free and applies the real rule above six hours',()=>{const context=vm.createContext({getBusinessRequiredBreakMinutes:centralTime.getBusinessRequiredBreakMinutes,getWorkedMinutesFromRange:centralTime.getWorkedMinutesFromRange});vm.runInContext(`${extract('recalculatePlanning2ShiftTimes')};this.recalculate=recalculatePlanning2ShiftTimes`,context);const exact=context.recalculate({type:'shift'},'09:00','15:00'),longer=context.recalculate({type:'shift'},'09:00','15:15');assert.equal(exact.pause,0);assert.equal(exact.breakMinutes,0);assert.equal(exact.minutes,centralTime.getWorkedMinutesFromRange('09:00','15:00',exact.pause));assert.equal(longer.pause,60);assert.equal(longer.breakMinutes,60);assert.equal(longer.minutes,centralTime.getWorkedMinutesFromRange('09:00','15:15',longer.pause))});

test('stale suggestion and every resolved non-work state refuse mutation and re-render',()=>{for(const type of ['vacation','sick','off','holiday','external-help']){const plan={schedule:{[isoDate]:{anna:{...shift,type}}},absences:[]},h=harness(plan,base,{resolved:false});assert.equal(h.api.applyPlanning2OptimizationSuggestion(base),false,type);assert.deepEqual(h.state(),plan);assert.equal(h.renders(),1);assert.equal(h.toasts.at(-1)[0],'Vorschlag ist nicht mehr aktuell.')}const plan={schedule:{[isoDate]:{anna:shift}},absences:[]},h=harness(plan,base,{fresh:[]});assert.equal(h.api.applyPlanning2OptimizationSuggestion(base),false);assert.deepEqual(h.state(),plan)});


test('applying one of two same-day gaps recomputes suggestions and rejects the old second proposal when its gap changed',()=>{const first={...base,currentStart:'09:00',currentEnd:'13:00',understaffingWindow:{start:780,end:845}},oldSecond={isoDate,employeeId:'ben',direction:'advance-start',currentStart:'10:05',currentEnd:'19:10',proposedStart:'09:00',proposedEnd:'19:10',understaffingWindow:{start:540,end:605}},newSecond={...oldSecond,understaffingWindow:{start:540,end:590}},benShift={...shift,start:'10:05',end:'19:10',withCheckout:true},employees=[{id:'anna',name:'Anna'},{id:'ben',name:'Ben'}],plan={schedule:{[isoDate]:{anna:shift,ben:benShift}},absences:[]},fresh=current=>current.schedule[isoDate].anna.end==='13:00'?[first,oldSecond]:[newSecond],h=harness(plan,first,{fresh,employees});assert.equal(h.api.applyPlanning2OptimizationSuggestion(first),true,'real extend-end proposal solves the later gap');assert.equal(h.state().schedule[isoDate].anna.end,'14:00');const afterFirst=structuredClone(h.state());assert.equal(h.api.applyPlanning2OptimizationSuggestion(oldSecond),false,'old advance-start proposal is stale after recomputation');assert.deepEqual(h.state(),afterFirst,'stale proposal does not mutate the recalculated plan');assert.equal(h.api.applyPlanning2OptimizationSuggestion(newSecond),true,'fresh advance-start proposal for the changed earlier gap remains applicable');assert.equal(h.state().schedule[isoDate].ben.start,'09:00');assert.equal(h.state().schedule[isoDate].ben.end,'19:10');assert.deepEqual(h.autofixes,[isoDate,isoDate])});

test('undo restores the byte-equivalent complete plan and is consumed after one use',()=>{const plan={weekFrom:'2026-08-01',schedule:{[isoDate]:{anna:shift}},absences:[{id:'x',type:'vacation'}],extra:{nested:true}},h=harness(plan,base);assert.equal(h.api.applyPlanning2OptimizationSuggestion(base),true);assert.equal(h.toasts.at(-1)[0],'Vorschlag übernommen');assert.equal(h.toasts.at(-1)[1],'Rückgängig');assert.equal(h.api.undoPlanning2Optimization(),true);assert.equal(JSON.stringify(h.state()),JSON.stringify(plan));assert.equal(h.api.undoPlanning2Optimization(),false)});

test('apply path is wired to fresh validation, complete autofixes, save, render, and compact action UI',()=>{assert.match(extract('applyPlanning2OptimizationSuggestion'),/getCurrentPlanning2OptimizationSuggestions/);assert.match(extract('applyPlanning2OptimizationSuggestion'),/applyPlanning2OptimizationAutofixes/);assert.match(extract('render'),/data-optimization/);assert.match(preview,/data-optimization/);assert.match(preview,/Rückgängig/)});
