const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { loadScripts } = require('./test-helpers');
const centralTime = loadScripts(['time-utils.js']);
const preview = fs.readFileSync('planung2-preview.html', 'utf8');
function extract(name) { const start=preview.indexOf(`function ${name}`); assert.notEqual(start,-1,`${name} exists`); let depth=0,open=false; for(let i=start;i<preview.length;i++){if(preview[i]==='{'){depth++;open=true}else if(preview[i]==='}'&&--depth===0&&open)return preview.slice(start,i+1)} throw Error(name) }
function loadApi(){const c=vm.createContext({iso:d=>d.toISOString().slice(0,10),mins:v=>{const [h,m]=v.split(':').map(Number);return h*60+m},hm:m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,getBusinessRequiredBreakMinutes:centralTime.getBusinessRequiredBreakMinutes,getWorkedMinutesFromRange:centralTime.getWorkedMinutesFromRange,getMonthlyPlanChangeFacts:(before,current)=>({changeType:current.start===before?.start?'SHIFT_EXTENDED_END':'SHIFT_EXTENDED_START',startDifferenceMinutes:before?c.mins(current.start)-c.mins(before.start):null,endDifferenceMinutes:before?c.mins(current.end)-c.mins(before.end):null,workMinutesDifference:before?(c.mins(current.end)-c.mins(current.start))-(c.mins(before.end)-c.mins(before.start)):c.mins(current.end)-c.mins(current.start)})});vm.runInContext([
 'function resolvedShiftTimes(r){return r?.type==="shift"?{start:r.sourceEntry.start,end:r.sourceEntry.end}:null}',
 'function getPlanning2EmployeeWeekEvaluation(e,d,r){let actual=r.reduce((n,x)=>n+(x.minutesForMonth||0),0),isGfb=e.roleKey==="GFB",target=isGfb?null:(e.targetMinutes??1800),difference=isGfb?0:actual-target;return{weeklyActualMinutes:actual,weeklyTargetMinutes:target,differenceMinutes:difference,isGfb,hasRegularFreeDay:e.hasFree!==false,summary:{actualMinutes:actual,targetMinutes:target,differenceMinutes:difference,isGfb},freeDay:{hasRegularFreeDay:e.hasFree!==false}}}',
 extract('evaluateResolvedDayCoverage'),extract('recalculatePlanning2ShiftTimes'),extract('isPlanning2FullDayShift'),extract('buildPlanning2OptimizationContext'),extract('getPlanning2AllowedAdjustmentTimes'),extract('escapePlanning2Html'),extract('planning2GapResolved'),extract('getPlanning2CandidateRankingData'),extract('comparePlanning2OptimizationCandidates'),extract('planning2ProblemId'),extract('getPlanning2CandidateBaselineChange'),extract('planning2GapOverlapMinutes'),extract('getPlanning2CoverageFacts'),extract('planning2DaysUntilShift'),extract('buildPlanning2CandidateFeatureProfile'),extract('summarizePlanning2CandidateRejections'),extract('generatePlanning2CandidateEvaluation'),extract('buildPlanning2ProblemCandidateGroups'),extract('getPlanning2CandidateRankingFeatures'),extract('planning2ExplanationMinutes'),extract('describePlanning2Candidate'),extract('generatePlanning2Candidates'),extract('rankPlanning2Candidates'),extract('getPlanning2CandidatesForProblem'),extract('buildPlanning2OptimizationSuggestions'),'this.api={buildPlanning2OptimizationContext,buildPlanning2OptimizationSuggestions,generatePlanning2Candidates,generatePlanning2CandidateEvaluation,buildPlanning2CandidateFeatureProfile,buildPlanning2ProblemCandidateGroups,summarizePlanning2CandidateRejections,getPlanning2CandidateRankingFeatures,describePlanning2Candidate,planning2DaysUntilShift,rankPlanning2Candidates,getPlanning2CandidatesForProblem,getPlanning2AllowedAdjustmentTimes,getPlanning2CandidateRankingData,comparePlanning2OptimizationCandidates,escapePlanning2Html,isPlanning2FullDayShift}'
].join(';'),c);c.api.setEvaluate=fn=>{c.evaluateResolvedDayCoverage=fn};return c.api}
const day=new Date('2026-08-24T00:00:00Z');
const shift=(start,end,minutesForMonth=0)=>({type:'shift',minutesForMonth,sourceEntry:{type:'shift',start,end}});
function suggestions(employees,entries){const api=loadApi(),resolved=entries.map(entry=>[entry]),context=api.buildPlanning2OptimizationContext(employees,[day],resolved);return{context,result:api.buildPlanning2OptimizationSuggestions(context),resolved}}

test('candidate generation retains every employee alternative for one stable problem',()=>{const api=loadApi(),resolved=[[shift('09:00','13:00')],[shift('09:30','13:00')]],context=api.buildPlanning2OptimizationContext([{id:'a',roleKey:'TZ'},{id:'b',roleKey:'TZ'}],[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const candidates=api.generatePlanning2Candidates(context),employees=new Set(candidates.map(item=>item.employeeId)),problems=new Set(candidates.map(item=>item.problemId));assert.deepEqual([...employees].sort(),['a','b']);assert.equal(problems.size,1);assert.equal([...problems][0],'2026-08-24|13:00|14:00|understaffing');assert.ok(candidates.every(item=>item.constraintResults.allowed))});

test('mixed end and start alternatives survive generation and ranking stays deterministic',()=>{const api=loadApi(),resolved=[[shift('09:00','13:00')],[shift('14:00','19:00')]],context=api.buildPlanning2OptimizationContext([{id:'a',roleKey:'TZ'},{id:'b',roleKey:'TZ'}],[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const candidates=api.generatePlanning2Candidates(context);assert.deepEqual([...new Set(candidates.map(item=>item.direction))].sort(),['advance-start','extend-end']);assert.equal(JSON.stringify(api.rankPlanning2Candidates(candidates).map(item=>item.candidateId)),JSON.stringify(api.rankPlanning2Candidates([...candidates].reverse()).map(item=>item.candidateId)))});

test('candidate evaluation exposes hard-constraint rejection reasons without mutating inputs',()=>{const api=loadApi(),resolved=[[shift('09:00','13:00',240)]],context=api.buildPlanning2OptimizationContext([{id:'g',roleKey:'GFB'}],[day],resolved,{g:{gfbMonthActualMinutes:2580,gfbMonthLimitMinutes:2580,gfbMonthRemainingMinutes:0}}),before=JSON.stringify(context);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};const snapshot=JSON.stringify(context);api.setEvaluate(()=>({ok:true,gaps:[]}));const evaluation=api.generatePlanning2CandidateEvaluation(context);assert.equal(evaluation.candidates.length,0);assert.ok(evaluation.rejected.some(item=>item.constraintResults.violations.some(v=>v.rule==='GFB_MONTH_LIMIT')));assert.equal(JSON.stringify(context),snapshot);assert.notEqual(before,snapshot)});

test('candidate reports unavailable baseline cleanly',()=>{const api=loadApi(),resolved=[[shift('09:00','13:00')]],context=api.buildPlanning2OptimizationContext([{id:'a',roleKey:'TZ'}],[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));assert.equal(JSON.stringify(api.generatePlanning2Candidates(context)[0].baselineChange),JSON.stringify({available:false,change:null}))});

test('candidate baseline facts use the baseline belonging to the candidate ISO month',()=>{const api=loadApi(),resolved=[[shift('09:00','13:00')]],baselinePlan={monthlyPlanBaselines:{'2026-08':{entries:{'2026-08-24':{a:{kind:'shift',start:'09:00',end:'12:30'}}}}}},context=api.buildPlanning2OptimizationContext([{id:'a',roleKey:'TZ'}],[day],resolved,null,null,baselinePlan);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const baseline=api.generatePlanning2Candidates(context)[0].baselineChange;assert.equal(baseline.available,true);assert.equal(baseline.change.changeType,'SHIFT_EXTENDED_END');assert.equal(baseline.change.endDifferenceMinutes,90)});

test('days until shift accepts Date, calendar-date and complete ISO references',()=>{const api=loadApi(),target='2026-09-05';assert.equal(api.planning2DaysUntilShift(target,new Date('2026-09-01T18:45:00Z')),4);assert.equal(api.planning2DaysUntilShift(target,'2026-09-01'),4);assert.equal(api.planning2DaysUntilShift(target,'2026-09-01T12:30:00Z'),4)});

test('boundary candidate exposes one mutation and neutral single-change disruption facts',()=>{const api=loadApi(),resolved=[[shift('09:00','14:00',300)]],baseline={monthlyPlanBaselines:{'2026-08':{entries:{'2026-08-24':{a:{kind:'shift',start:'09:00',end:'14:00'}}}}}},context=api.buildPlanning2OptimizationContext([{id:'a',roleKey:'TZ'}],[day],resolved,null,null,baseline,'2026-08-20');context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:840,end:900}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const candidate=api.generatePlanning2Candidates(context).find(x=>x.proposedEnd==='15:00'),profile=candidate.features;assert.equal(candidate.mutations.length,1);assert.equal(profile.disruption.affectedEmployeeCount,1);assert.equal(profile.disruption.affectedDateCount,1);assert.equal(profile.disruption.existingWorkdayAdjusted,true);assert.equal(profile.disruption.touchesRegularFreeDay,false);assert.equal(profile.baseline.workdayAdded,false);assert.equal(profile.baseline.changedBoundaryCount,1);assert.equal(profile.baseline.absoluteEndDifferenceMinutes,60);assert.equal(profile.disruption.totalBoundaryShiftMinutes,60);assert.equal(profile.timing.daysUntilShift,4);assert.equal(profile.coverage.targetGapMinutesBefore,60);assert.equal(profile.coverage.targetGapMinutesAfter,0);assert.equal(profile.coverage.targetGapMinutesResolved,60);assert.equal(profile.coverage.newUnderstaffingCreated,false)});

test('feature profile preserves two changed boundaries and circumstance origin as neutral facts',()=>{const api=loadApi(),candidate={problemId:'p',candidateId:'c',isoDate:'2026-09-05',employeeId:'a',roleKey:'TZ',mutations:[{isoDate:'2026-09-05',employeeId:'a',before:{start:'09:00',end:'14:00'},after:{start:'12:00',end:'17:00'}}],baselineChange:{available:true,change:{changeType:'SHIFT_MOVED_OR_RESIZED',changeOrigin:'circumstance',startDifferenceMinutes:180,endDifferenceMinutes:180,workMinutesDifference:0,workdayAdded:false,workdayRemoved:false}},coverageBefore:{gaps:[{kind:'understaffing',start:720,end:780}]},coverageAfter:{gaps:[{kind:'understaffing',start:750,end:780}]},understaffingWindow:{kind:'understaffing',start:720,end:780},resolvesTargetGap:false},profile=api.buildPlanning2CandidateFeatureProfile(candidate,{referenceDate:'2026-09-01'});assert.equal(profile.baseline.changeOrigin,'circumstance');assert.equal(profile.baseline.changedBoundaryCount,2);assert.equal(profile.baseline.absoluteStartDifferenceMinutes,180);assert.equal(profile.baseline.absoluteEndDifferenceMinutes,180);assert.equal(profile.disruption.totalBoundaryShiftMinutes,360);assert.equal(profile.coverage.targetGapMinutesAfter,30);assert.equal(profile.coverage.targetGapMinutesResolved,30);assert.equal(profile.coverage.coverageImproved,true)});

test('problem groups retain alternatives, separate gaps and aggregate rejection rules',()=>{const api=loadApi(),resolved=[[shift('09:00','13:00')],[shift('09:00','13:00')]],context=api.buildPlanning2OptimizationContext([{id:'a',roleKey:'TZ'},{id:'g',roleKey:'GFB'}],[day],resolved,null,null);context.employees[1].gfbMonthRemainingMinutes=0;context.employees[1].gfbMonthStatusesByIsoDate={'2026-08-24':{gfbMonthRemainingMinutes:0}};context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840},{kind:'understaffing',start:840,end:900}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const groups=api.buildPlanning2ProblemCandidateGroups(context);assert.equal(groups.length,2);assert.ok(groups[0].candidates.some(x=>x.employeeId==='a'));assert.ok(groups[0].rejectionSummary.GFB_MONTH_LIMIT>0);assert.notEqual(groups[0].problemId,groups[1].problemId)});

test('rejected-only problem remains grouped but render suppresses zero-alternative buttons',()=>{const api=loadApi(),context=api.buildPlanning2OptimizationContext([{id:'g',roleKey:'GFB'}],[day],[[shift('09:00','13:00',240)]],{g:{gfbMonthActualMinutes:2580,gfbMonthLimitMinutes:2580,gfbMonthRemainingMinutes:0}});context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const groups=api.buildPlanning2ProblemCandidateGroups(context);assert.equal(groups.length,1);assert.equal(groups[0].candidates.length,0);assert.ok(groups[0].rejectedCount>0);assert.ok(groups[0].rejectionSummary.GFB_MONTH_LIMIT>0);assert.match(extract('render'),/dayGroups\.filter\(group=>group\.candidates\.length>0\)\.map/)});

test('ranking features and factual explanation are deterministic and versioned',()=>{const api=loadApi(),resolved=[[shift('09:00','13:00')]],context=api.buildPlanning2OptimizationContext([{id:'a',name:'Anna',roleKey:'TZ'}],[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const candidate=api.generatePlanning2Candidates(context)[0],left=api.getPlanning2CandidateRankingFeatures(candidate),right=api.getPlanning2CandidateRankingFeatures({...candidate});assert.equal(JSON.stringify(left),JSON.stringify(right));assert.equal(api.rankPlanning2Candidates([candidate])[0].rankingVersion,'heuristic-v1');const explanation=api.describePlanning2Candidate(candidate);assert.match(explanation.title,/Anna/);assert.ok(explanation.facts.includes('schließt die Unterbesetzung vollständig'));assert.ok(explanation.facts.includes('keine neue Unterbesetzung'));assert.ok(!explanation.facts.some(text=>/Punkte|Score/.test(text)))});

test('cross-month candidates select baseline snapshots from their own ISO dates',()=>{const api=loadApi(),days=[new Date('2026-09-30T00:00:00Z'),new Date('2026-10-01T00:00:00Z')],resolved=[[shift('09:00','13:00'),shift('09:00','13:00')]],baseline={monthlyPlanBaselines:{'2026-09':{entries:{'2026-09-30':{a:{kind:'shift',start:'09:00',end:'12:00'}}}},'2026-10':{entries:{'2026-10-01':{a:{kind:'shift',start:'09:00',end:'12:30'}}}}}},context=api.buildPlanning2OptimizationContext([{id:'a',roleKey:'TZ'}],days,resolved,null,null,baseline);context.days.forEach(dayContext=>dayContext.coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840}]});api.setEvaluate(()=>({ok:true,gaps:[]}));const candidates=api.generatePlanning2Candidates(context),september=candidates.find(x=>x.isoDate==='2026-09-30'&&x.proposedEnd==='14:00'),october=candidates.find(x=>x.isoDate==='2026-10-01'&&x.proposedEnd==='14:00');assert.equal(september.features.baseline.endDifferenceMinutes,120);assert.equal(october.features.baseline.endDifferenceMinutes,90)});

test('preview exposes a compact alternatives sheet without making alternatives actionable',()=>{assert.match(preview,/data-candidate-problem/);assert.match(preview,/id="candidateDebugOverlay"/);assert.match(extract('openPlanning2CandidateDebug'),/describePlanning2Candidate/);assert.doesNotMatch(extract('openPlanning2CandidateDebug'),/applyPlanning2OptimizationSuggestion/)});

test('grid generation rejects arbitrary gap minutes and keeps 30-minute choices before quarters',()=>{const api=loadApi();for(const minute of [5,10,20,25,35,40,50,55]){const times=api.getPlanning2AllowedAdjustmentTimes('13:00',14*60+minute,'extend-end');assert.ok(times.every(x=>[0,15,30,45].includes(x.minutes%60)));assert.ok(!times.some(x=>x.minutes%60===minute),`:${minute} was copied`);const quarter=times.findIndex(x=>x.minutes%30!==0);assert.ok(quarter<0||times.slice(0,quarter).every(x=>x.minutes%30===0))}assert.deepEqual(Array.from(api.getPlanning2AllowedAdjustmentTimes('13:00',845,'extend-end'),x=>x.time),['14:00','14:15'])});

test('13:00–14:05 is exact while the read-only suggestion ends at 14:00',()=>{const employees=[{id:'base',roleKey:'TZ'},{id:'anna',name:'Anna',roleKey:'TZ',functionKey:'SV'},{id:'late',roleKey:'TZ'}],entries=[shift('08:55','19:10',600),shift('09:00','13:00',240),shift('14:05','19:10',305)],before=JSON.stringify({employees,entries}),built=suggestions(employees,entries),anna=built.result.find(x=>x.employeeId==='anna');assert.deepEqual(Array.from(built.context.days[0].coverage.gaps,g=>[g.start,g.end]),[[780,845]]);assert.equal(anna.proposedEnd,'14:00');assert.equal(anna.timeGrid,'hour');assert.equal(anna.projectedWeeklyActualMinutes,300);assert.equal(JSON.stringify({employees,entries}),before)});

test('quarter-hour is tested only after an insufficient 30-minute simulation',()=>{const api=loadApi(),employees=[{id:'anna',name:'Anna',roleKey:'TZ'}],resolved=[[shift('09:00','13:00')]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:875,required:2}]};api.setEvaluate(entries=>{const minute=Number(entries[0].sourceEntry.end.slice(0,2))*60+Number(entries[0].sourceEntry.end.slice(3));return{ok:minute>=885,gaps:minute>=885?[]:[{kind:'understaffing',start:780,end:875}]}});const result=api.buildPlanning2OptimizationSuggestions(context)[0];assert.equal(result.proposedEnd,'14:45');assert.equal(result.timeGrid,'quarter-hour')});

test('30-minute grid beats a quarter-hour option whenever its simulation succeeds',()=>{const api=loadApi(),employees=[{id:'half',roleKey:'TZ'}],resolved=[[shift('09:00','13:00')]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:875,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const result=api.buildPlanning2OptimizationSuggestions(context)[0];assert.equal(result.proposedEnd,'14:30');assert.equal(result.timeGrid,'half-hour')});

test('advance-start follows the same grid priority and preserves an existing 19:10 end',()=>{const api=loadApi(),employees=[{id:'ben',roleKey:'TZ'}],resolved=[[shift('14:05','19:10')]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:845,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const ben=api.buildPlanning2OptimizationSuggestions(context)[0];assert.equal(ben.proposedStart,'13:00');assert.equal(ben.proposedEnd,'19:10');assert.notEqual(ben.proposedStart,'08:55')});

test('changing an end preserves 08:55 and general suggestions create neither special boundary',()=>{const built=suggestions([{id:'opener',roleKey:'TZ'},{id:'base',roleKey:'TZ'},{id:'late',roleKey:'TZ'}],[shift('08:55','13:00'),shift('09:00','19:10'),shift('14:05','19:10')]);const opener=built.result.find(x=>x.employeeId==='opener');assert.equal(opener.proposedStart,'08:55');assert.equal(opener.proposedEnd,'14:00');assert.ok(built.result.every(x=>x.proposedStart!=='08:55'||x.currentStart==='08:55'));assert.ok(built.result.every(x=>x.proposedEnd!=='19:10'||x.currentEnd==='19:10'))});

test('only resolved shifts qualify even when every non-work state hides old shift times',()=>{for(const type of ['vacation','sick','off','holiday','external-help','empty']){const built=suggestions([{id:'base',roleKey:'TZ'},{id:'hidden',roleKey:'TZ'},{id:'late',roleKey:'TZ'}],[shift('08:55','19:10'),{type,sourceEntry:{type:'shift',start:'09:00',end:'13:00'}},shift('14:05','19:10')]);assert.ok(!built.result.some(x=>x.employeeId==='hidden'),type)}});

test('a completely closed holiday produces no optimization suggestions',()=>{const api=loadApi(),employees=[{id:'anna',roleKey:'TZ'},{id:'ben',roleKey:'TZ'}],holiday={type:'holiday',isHoliday:true,label:'H',minutesForBranch:0},resolved=[[holiday],[holiday]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);assert.equal(context.days[0].coverage.ok,true);assert.deepEqual(Array.from(context.days[0].coverage.gaps),[]);assert.deepEqual(Array.from(api.buildPlanning2OptimizationSuggestions(context)),[])});

test('two gaps remain separate and independently suggest both sides of the same middle shift',()=>{const built=suggestions([{id:'base',roleKey:'TZ'},{id:'middle',roleKey:'TZ'},{id:'morning',roleKey:'TZ'},{id:'late',roleKey:'TZ'}],[shift('08:55','19:10'),shift('10:05','13:00'),shift('08:55','09:00'),shift('14:05','19:10')]);assert.deepEqual(Array.from(built.context.days[0].coverage.gaps,g=>[g.start,g.end]),[[540,605],[780,845]]);assert.equal(built.result.length,2);assert.deepEqual(Array.from(built.result,x=>[x.understaffingWindow.start,x.understaffingWindow.end]),[[540,605],[780,845]])});

test('GFB is eligible without an artificial target or projected difference',()=>{const built=suggestions([{id:'base',roleKey:'TZ'},{id:'gfb',roleKey:'GFB'},{id:'late',roleKey:'TZ',targetMinutes:100}],[shift('08:55','19:10'),shift('09:00','13:00',240),shift('14:05','19:10',305)]),gfb=built.result.find(x=>x.employeeId==='gfb');assert.equal(gfb.weeklyTargetMinutes,null);assert.equal(gfb.projectedDifferenceMinutes,null)});

test('central ranking prefers an employee below target over one above target',()=>{const built=rankSuggestions([{id:'plus',roleKey:'TZ',targetMinutes:100,actual:300},{id:'minus',roleKey:'TZ',targetMinutes:500,actual:300}]);assert.equal(built.result[0].employeeId,'minus');assert.equal(built.result[0].ranking.targetStatus,'under')});

test('central ranking prefers the larger useful deficit',()=>{const built=rankSuggestions([{id:'small-minus',roleKey:'TZ',targetMinutes:360,actual:300},{id:'large-minus',roleKey:'TZ',targetMinutes:600,actual:300}]);assert.equal(built.result[0].employeeId,'large-minus');assert.equal(built.result[0].ranking.deficitMinutes,300)});

test('a meaningfully larger deficit wins despite a somewhat longer extension',()=>{const built=rankSuggestions([{id:'large-minus',roleKey:'TZ',targetMinutes:900,actual:300},{id:'short-small-minus',roleKey:'TZ',targetMinutes:360,actual:300}],['13:00','13:30']);assert.equal(built.result[0].employeeId,'large-minus');assert.equal(built.result[0].changeMinutes,60)});

test('TZ below target ranks before an eligible GFB',()=>{const built=rankSuggestions([{id:'gfb',roleKey:'GFB',actual:300},{id:'tz-minus',roleKey:'TZ',targetMinutes:600,actual:300}]);assert.equal(built.result[0].employeeId,'tz-minus')});

test('GFB ranks before normal candidates that already met or exceeded target',()=>{const built=rankSuggestions([{id:'plus',roleKey:'TZ',targetMinutes:200,actual:300},{id:'gfb',roleKey:'GFB',actual:300},{id:'met',roleKey:'TZ',targetMinutes:300,actual:300}]);assert.equal(built.result[0].employeeId,'gfb')});

test('an otherwise suitable employee without a regular free day ranks later',()=>{const built=rankSuggestions([{id:'no-free',roleKey:'TZ',targetMinutes:600,actual:300,hasFree:false},{id:'with-free',roleKey:'TZ',targetMinutes:600,actual:300,hasFree:true}]);assert.equal(built.result[0].employeeId,'with-free');assert.equal(built.result[0].ranking.hasRegularFreeDay,true)});

test('a regular free day outweighs a small adjustment saving at the same deficit',()=>{const built=rankSuggestions([{id:'with-free',roleKey:'TZ',targetMinutes:600,actual:300,hasFree:true},{id:'no-free',roleKey:'TZ',targetMinutes:600,actual:300,hasFree:false}],['13:00','13:30']);assert.equal(built.result[0].employeeId,'with-free');assert.equal(built.result[0].changeMinutes,60)});

test('GFB ranking has no invented weekly target, difference, or deficit',()=>{const api=loadApi(),ranking=api.getPlanning2CandidateRankingData({employeeId:'gfb',isGfb:true,weeklyTargetMinutes:null,differenceMinutes:0,weeklyActualMinutes:300,changeMinutes:60,hasRegularFreeDay:true});assert.equal(ranking.targetStatus,'gfb');assert.equal(ranking.deficitMinutes,null)});

test('smaller necessary adjustment breaks ties between otherwise equal candidates',()=>{const built=rankSuggestions([{id:'long',roleKey:'TZ',targetMinutes:600,actual:300},{id:'short',roleKey:'TZ',targetMinutes:600,actual:300}],['13:00','13:30']);assert.equal(built.result[0].employeeId,'short');assert.equal(built.result[0].changeMinutes,30)});

test('candidate is rejected when its simulation creates a new understaffing gap',()=>{const api=loadApi(),employees=[{id:'unsafe',roleKey:'TZ',targetMinutes:600},{id:'safe',roleKey:'TZ',targetMinutes:600}],resolved=[[shift('09:00','13:00',300)],[shift('09:00','13:00',300)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:845,required:2}]};api.setEvaluate(entries=>entries[0].sourceEntry.end!=='13:00'?{ok:false,gaps:[{kind:'understaffing',start:780,end:840},{kind:'understaffing',start:900,end:930}]}:{ok:true,gaps:[]});const result=api.buildPlanning2OptimizationSuggestions(context);assert.equal(result[0].employeeId,'safe')});

function rankSuggestions(people,ends){const api=loadApi(),resolved=(ends||people.map(()=> '13:00')).map((end,index)=>[shift('09:00',end,people[index].actual||0)]),context=api.buildPlanning2OptimizationContext(people,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:845,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));return{result:api.buildPlanning2OptimizationSuggestions(context),context}}

test('Saturday dates work normally and every simulation leaves nested inputs byte-identical',()=>{const employees=[{id:'base',roleKey:'TZ'},{id:'anna',roleKey:'TZ'},{id:'late',roleKey:'TZ'}],entries=[shift('08:55','19:10'),shift('09:00','13:00'),shift('14:05','19:10')],resolved=entries.map(x=>[x]),before=JSON.stringify({employees,resolved}),api=loadApi(),context=api.buildPlanning2OptimizationContext(employees,[new Date('2026-08-29T00:00:00Z')],resolved);api.buildPlanning2OptimizationSuggestions(context);assert.equal(context.days[0].isoDate,'2026-08-29');assert.equal(JSON.stringify({employees,resolved}),before)});

test('suggestion employee names are centrally HTML escaped',()=>{assert.equal(loadApi().escapePlanning2Html(`A&B <C> \"D\" 'E'`),'A&amp;B &lt;C&gt; &quot;D&quot; &#39;E&#39;');assert.match(extract('render'),/escapePlanning2Html\(item\.employeeName\)/)});

test('GFB month budget allows exactly 42:00 plus 1:00',()=>{const api=loadApi(),employees=[{id:'gfb',roleKey:'GFB'}],resolved=[[shift('09:00','13:00',240)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved,{gfb:{gfbMonthActualMinutes:2520,gfbMonthLimitMinutes:2580,gfbMonthRemainingMinutes:60}});context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const result=api.buildPlanning2OptimizationSuggestions(context);assert.equal(result.length,1);assert.equal(result[0].changeMinutes,60);assert.equal(result[0].gfbMonthActualMinutes,2520);assert.equal(result[0].gfbMonthLimitMinutes,2580);assert.equal(result[0].gfbMonthRemainingMinutes,60)});

test('GFB month budget rejects 42:30 plus 1:00',()=>{const api=loadApi(),employees=[{id:'gfb',roleKey:'GFB'}],resolved=[[shift('09:00','13:00',240)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved,{gfb:{gfbMonthActualMinutes:2550,gfbMonthLimitMinutes:2580,gfbMonthRemainingMinutes:30}});context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));assert.deepEqual(Array.from(api.buildPlanning2OptimizationSuggestions(context)),[])});

test('GFB budget filtering does not change normal employee eligibility',()=>{const api=loadApi(),employees=[{id:'normal',roleKey:'TZ',targetMinutes:600}],resolved=[[shift('09:00','13:00',240)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));assert.equal(api.buildPlanning2OptimizationSuggestions(context)[0].employeeId,'normal')});

test('GFB budget uses additional monthly work minutes across the break threshold',()=>{const api=loadApi(),employees=[{id:'gfb',roleKey:'GFB'}],resolved=[[shift('09:00','14:30',330)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved,{gfb:{gfbMonthActualMinutes:2580,gfbMonthLimitMinutes:2580,gfbMonthDifferenceMinutes:0,gfbMonthRemainingMinutes:0}});context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:870,end:930,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const result=api.buildPlanning2OptimizationSuggestions(context);assert.equal(result.length,1);assert.equal(result[0].changeMinutes,60);assert.equal(result[0].gfbMonthAdditionalMinutes,0);assert.equal(result[0].proposedEnd,'15:30')});

test('GFB already above 43:00 cannot receive additional monthly work minutes',()=>{const api=loadApi(),employees=[{id:'gfb',roleKey:'GFB'}],resolved=[[shift('09:00','13:00',240)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved,{gfb:{gfbMonthActualMinutes:2640,gfbMonthLimitMinutes:2580,gfbMonthDifferenceMinutes:-60,gfbMonthRemainingMinutes:0}});context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:840,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));assert.deepEqual(Array.from(api.buildPlanning2OptimizationSuggestions(context)),[])});


test('full-day classification centrally recognizes every Planning 2 boundary combination without calculating work minutes',()=>{const api=loadApi();for(const start of ['08:55','09:00'])for(const end of ['19:00','19:10'])assert.equal(api.isPlanning2FullDayShift(start,end),true,`${start}–${end}`);for(const [start,end] of [['09:00','15:00'],['08:55','15:00'],['10:00','20:00']])assert.equal(api.isPlanning2FullDayShift(start,end),false,`${start}–${end}`)});

function fullDaySuggestions(employees){const api=loadApi(),resolved=employees.map(()=>[shift('09:00','13:00',240)]),context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:1140,required:2}]};api.setEvaluate(entries=>entries.some(entry=>entry.sourceEntry.end==='19:00')?{ok:true,gaps:[]}:{ok:false,gaps:[{kind:'understaffing',start:780,end:1140}]});return{api,context,result:api.buildPlanning2OptimizationSuggestions(context)}}

test('approved employee may receive a 09:00–19:00 suggestion',()=>{const built=fullDaySuggestions([{id:'approved',roleKey:'TZ',planning2FullDayCandidate:true}]);assert.equal(built.context.employees[0].planning2FullDayCandidate,true);assert.equal(built.result[0].employeeId,'approved');assert.equal(built.result[0].proposedEnd,'19:00')});

test('employee without approval cannot receive the same full-day suggestion',()=>{const built=fullDaySuggestions([{id:'regular',roleKey:'TZ'}]);assert.equal(built.context.employees[0].planning2FullDayCandidate,false);assert.deepEqual(Array.from(built.result),[])});

test('short extensions remain available without full-day approval',()=>{const built=rankSuggestions([{id:'regular',roleKey:'TZ',targetMinutes:600}]);assert.equal(built.result[0].employeeId,'regular');assert.equal(built.result[0].proposedEnd,'14:00')});

test('only the approved candidate is considered when equivalent employees can solve a full-day gap',()=>{const built=fullDaySuggestions([{id:'regular',roleKey:'TZ',targetMinutes:900},{id:'approved',roleKey:'TZ',targetMinutes:900,planning2FullDayCandidate:true}]);assert.deepEqual(Array.from(built.result,item=>item.employeeId),['approved']);assert.equal(built.result[0].proposedEnd,'19:00')});

test('an existing full-day shift remains valid without approval',()=>{const api=loadApi(),employees=[{id:'existing',roleKey:'TZ'}],resolved=[[shift('09:00','19:00',540)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);assert.equal(context.employees[0].shifts[0].end,'19:00');assert.equal(api.isPlanning2FullDayShift(context.employees[0].shifts[0].start,context.employees[0].shifts[0].end),true);assert.deepEqual(Array.from(api.buildPlanning2OptimizationSuggestions(context)),[])});

test('normal weekly projection uses central worked-minute delta rather than attendance extension',()=>{const api=loadApi(),employees=[{id:'normal',roleKey:'TZ',targetMinutes:600}],resolved=[[shift('09:00','14:30',330)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:870,end:930,required:2}]};api.setEvaluate(()=>({ok:true,gaps:[]}));const result=api.buildPlanning2OptimizationSuggestions(context)[0],current=centralTime.getWorkedMinutesFromRange('09:00','14:30',centralTime.getBusinessRequiredBreakMinutes('09:00','14:30')),proposed=centralTime.getWorkedMinutesFromRange('09:00','15:30',centralTime.getBusinessRequiredBreakMinutes('09:00','15:30'));assert.equal(result.changeMinutes,60,'attendance is extended by one hour');assert.equal(result.actualChangeMinutes,proposed-current);assert.equal(result.actualChangeMinutes,0,'the central break transition consumes the attendance extension');assert.equal(result.projectedWeeklyActualMinutes,330);assert.equal(result.projectedDifferenceMinutes,-270)});

test('full-day suggestion impact matches central time rules while preserving special opening boundaries',()=>{for(const start of ['08:55','09:00']){const api=loadApi(),end='19:00',currentEnd='13:00',currentMinutes=centralTime.getWorkedMinutesFromRange(start,currentEnd,centralTime.getBusinessRequiredBreakMinutes(start,currentEnd)),employees=[{id:'approved',roleKey:'TZ',planning2FullDayCandidate:true,targetMinutes:900}],resolved=[[shift(start,currentEnd,currentMinutes)]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:780,end:1140,required:2}]};api.setEvaluate(entries=>entries[0].sourceEntry.end===end?{ok:true,gaps:[]}:{ok:false,gaps:[{kind:'understaffing',start:780,end:1140}]});const result=api.buildPlanning2OptimizationSuggestions(context)[0],proposedMinutes=centralTime.getWorkedMinutesFromRange(start,end,centralTime.getBusinessRequiredBreakMinutes(start,end));assert.ok(result,`${start}–${end}`);assert.equal(result.proposedStart,start);assert.equal(result.proposedEnd,end);assert.equal(result.actualChangeMinutes,proposedMinutes-currentMinutes);assert.equal(result.projectedWeeklyActualMinutes,currentMinutes+result.actualChangeMinutes)}});

test('special gap boundaries are exact and precede normal grid fallbacks',()=>{
  const api=loadApi();
  assert.deepEqual(Array.from(api.getPlanning2AllowedAdjustmentTimes('15:00',1150,'extend-end'),x=>x.time),['19:10','19:00']);
  assert.deepEqual(Array.from(api.getPlanning2AllowedAdjustmentTimes('10:00',535,'advance-start'),x=>x.time),['08:55','09:00']);
  assert.ok(!api.getPlanning2AllowedAdjustmentTimes('15:00',1145,'extend-end').some(x=>x.time==='19:10'));
  assert.ok(!api.getPlanning2AllowedAdjustmentTimes('10:00',540,'advance-start').some(x=>x.time==='08:55'));
});

test('gap ending at 19:10 proposes exact checkout boundary rather than 19:15',()=>{
  const api=loadApi(),employees=[{id:'anna',name:'Anna',roleKey:'TZ',planning2FullDayCandidate:true}],resolved=[[shift('09:00','15:00')]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);
  context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:900,end:1150,required:2}]};
  api.setEvaluate(entries=>entries[0].sourceEntry.end==='19:10'?{ok:true,gaps:[]}:{ok:false,gaps:[{kind:'understaffing',start:900,end:1150}]});
  const result=api.buildPlanning2OptimizationSuggestions(context)[0];
  assert.equal(result.proposedEnd,'19:10');
  assert.notEqual(result.proposedEnd,'19:15');
  const pause=centralTime.getBusinessRequiredBreakMinutes(result.proposedStart,result.proposedEnd);
  assert.equal(pause,70);
  assert.equal(centralTime.getWorkedMinutesFromRange(result.proposedStart,result.proposedEnd,pause),540);
});

test('19:10 full-day approval cannot be bypassed by extending to 19:15',()=>{
  const api=loadApi(),employees=[{id:'anna',name:'Anna',roleKey:'TZ',planning2FullDayCandidate:false}],resolved=[[shift('09:00','15:00')]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);
  context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:900,end:1150,required:2}]};
  api.setEvaluate(entries=>mins(entries[0].sourceEntry.end)>=1150?{ok:true,gaps:[]}:{ok:false,gaps:[{kind:'understaffing',start:900,end:1150}]});
  const result=api.buildPlanning2OptimizationSuggestions(context);
  assert.equal(result.length,0);
  assert.ok(!result.some(item=>item.proposedEnd==='19:10'||item.proposedEnd==='19:15'));
});

test('gap starting at 08:55 proposes the exact opening boundary',()=>{
  const api=loadApi(),employees=[{id:'ben',name:'Ben',roleKey:'TZ',planning2FullDayCandidate:true}],resolved=[[shift('10:00','19:10')]],context=api.buildPlanning2OptimizationContext(employees,[day],resolved);
  context.days[0].coverage={ok:false,gaps:[{kind:'understaffing',start:535,end:600,required:2}]};
  api.setEvaluate(entries=>entries[0].sourceEntry.start==='08:55'?{ok:true,gaps:[]}:{ok:false,gaps:[{kind:'understaffing',start:535,end:600}]});
  assert.equal(api.buildPlanning2OptimizationSuggestions(context)[0].proposedStart,'08:55');
});
