const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const centralTime = require('../time-utils.js');

const preview = fs.readFileSync('planung2-preview.html', 'utf8');
function extract(name) { const start=preview.indexOf(`function ${name}`); assert.notEqual(start,-1); let depth=0,open=false; for(let i=start;i<preview.length;i++){if(preview[i]==='{'){depth++;open=true}else if(preview[i]==='}'&&--depth===0&&open)return preview.slice(start,i+1)} throw Error(name) }
function api(followUp) {
  const c=vm.createContext({Date, getBusinessRequiredBreakMinutes:centralTime.getBusinessRequiredBreakMinutes, getWorkedMinutesFromRange:centralTime.getWorkedMinutesFromRange});
  vm.runInContext(fs.readFileSync('time-utils.js','utf8'),c); vm.runInContext(fs.readFileSync('employee-availability.js','utf8'),c);
  vm.runInContext(`function mins(v){let [h,m]=v.split(':').map(Number);return h*60+m} function hm(m){return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')} function resolvedShiftTimes(r){return r?.type==='shift'?{start:r.sourceEntry.start,end:r.sourceEntry.end}:null} function planning2ProblemId(d,g){return d+'|'+g.start+'|'+g.end} function planning2GapResolved(c,g){return !(c.gaps||[]).some(x=>x.start<g.end&&x.end>g.start)} function getPlanning2CandidateBaselineChange(){return {available:false,change:null}} function buildPlanning2CandidateFeatureProfile(){return {}} function isPlanning2FullDayShift(s,e){return ['08:55','09:00'].includes(s)&&['19:00','19:10'].includes(e)} ${extract('recalculatePlanning2ShiftTimes')} ${extract('getPlanning2EmptyDayShiftWindows')} ${extract('getPlanning2RealFreeDayCount')} ${extract('generatePlanning2EmptyDayCandidates')}; this.run=generatePlanning2EmptyDayCandidates`,c);
  c.evaluateResolvedDayCoverage=entries=>{const shifts=entries.filter(x=>x?.type==='shift'); return shifts.length?{ok:true,gaps:[]}:{ok:false,gaps:[{kind:'understaffing',start:900,end:1020}]}};
  if(followUp)c.evaluatePlanning2CandidateFollowUpRules=followUp;
  return c.run;
}
function context({iso='2026-08-24',entry=null,employee={},free=2,gfb=false,fullDayCandidate=true}={}) { const entries=Array(6).fill({type:'shift',sourceEntry:{start:'09:00',end:'12:00'}}); entries[0]=entry; for(let i=1;i<free;i++)entries[i]=null; const person={employeeId:'e',name:'E',sourceEmployee:employee,resolvedEntries:entries,planning2FullDayCandidate:fullDayCandidate,evaluation:{weeklyActualMinutes:0,weeklyTargetMinutes:gfb?null:1800,differenceMinutes:gfb?0:-1800,isGfb:gfb},gfbMonthActualMinutes:gfb?2400:null,gfbMonthLimitMinutes:gfb?2580:null,gfbMonthRemainingMinutes:gfb?180:null}; return {employees:[person],days:[{isoDate:iso,dayIndex:0,resolvedEntries:[entry],coverage:{ok:false,gaps:[{kind:'understaffing',start:900,end:1020}]}}]}; }
const rules=x=>x.flatMap(c=>c.constraintResults.violations.map(v=>v.rule));

test('empty day creates multiple 15-minute windows of at least three hours, including both sides of a short gap',()=>{const out=api()(context()); assert.ok(out.candidates.length>2); assert.ok(out.candidates.every(x=>x.changeMinutes>=180)); const windows=out.candidates.map(x=>`${x.proposedStart}-${x.proposedEnd}`); assert.ok(windows.includes('14:00-17:00')); assert.ok(windows.includes('15:00-18:00'));});
test('a full empty-day shift is eligible without the legacy full-day opt-in when all hard constraints pass',()=>{const value=context({fullDayCandidate:false,employee:{availability:{general:{earliestStart:'08:55',latestEnd:'19:10',maxShiftMinutes:615}}}}); value.days[0].coverage.gaps=[{kind:'understaffing',start:535,end:1150}]; const out=api()(value); const fullDay=out.candidates.find(x=>x.proposedStart==='08:55'&&x.proposedEnd==='19:10'); assert.ok(fullDay); assert.ok(!fullDay.constraintResults.violations.some(v=>v.rule==='FULL_DAY_NOT_ALLOWED'));});
test('vacation, sickness, holiday and AG-free are hard blocked rather than converted',()=>{for(const type of ['vacation','sick','holiday','off']){const out=api()(context({entry:{type}})); assert.equal(out.candidates.length,0,type); assert.ok(rules(out.rejected).includes('DAY_NOT_EMPTY'));}});
test('availability boundaries and maximum duration are hard constraints',()=>{const out=api()(context({employee:{availability:{general:{earliestStart:'14:00',latestEnd:'18:00',maxShiftMinutes:180}}}})); assert.ok(out.candidates.length); assert.ok(out.candidates.every(x=>x.proposedStart>='14:00'&&x.proposedEnd<='18:00'&&x.changeMinutes<=180)); assert.ok(rules(out.rejected).includes('EMPLOYEE_AVAILABILITY'));});
test('Sunday is excluded and last real free day requests a machine-readable package mutation',()=>{assert.ok(rules(api()(context({iso:'2026-08-30'})).rejected).includes('SUNDAY_EXCLUDED')); const out=api()(context({free:1})); assert.equal(out.candidates.length,0); const item=out.rejected.find(x=>x.requiresCompensatingPackage); assert.equal(item.requiredPackageMutation.type,'CREATE_REAL_FREE_DAY'); assert.ok(item.constraintResults.violations.some(v=>v.rule==='COMPENSATING_FREE_DAY_MUTATION_REQUIRED'));});
test('GFB budget is never exceeded but an exact three-hour remainder is usable',()=>{let ok=context({gfb:true}); assert.ok(api()(ok).candidates.some(x=>x.actualChangeMinutes===180)); ok.employees[0].gfbMonthRemainingMinutes=179; const out=api()(ok); assert.equal(out.candidates.length,0); assert.ok(rules(out.rejected).includes('GFB_MONTH_LIMIT'));});
test('08:55 and 19:10 remain exact grid boundaries and follow-up violations reject candidates',()=>{let morning=context(); morning.days[0].coverage.gaps=[{kind:'understaffing',start:535,end:600}]; let out=api()(morning); assert.ok(out.candidates.some(x=>x.proposedStart==='08:55')); let evening=context(); evening.days[0].coverage.gaps=[{kind:'understaffing',start:1080,end:1150}]; out=api(()=>({rules:[],requiredFollowUpMutations:[{reason:'CARRYOVER_OPENER'}],touchesCarryoverRule:true,valid:false,violations:[{rule:'CARRYOVER_OPENER_RULE'}]}))(evening); assert.equal(out.candidates.length,0); assert.ok(rules(out.rejected).includes('CARRYOVER_OPENER_RULE')); assert.ok(out.rejected.some(x=>x.proposedEnd==='19:10'));});
test('generation and every simulation are side-effect free',()=>{const value=context(),before=JSON.stringify(value); api()(value); assert.equal(JSON.stringify(value),before);});
